# Generated by Django 3.1.7 on 2021-09-18 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название изображения')),
                ('url', models.SlugField(blank=True, null=True, verbose_name='URL изображения')),
                ('picture', models.ImageField(upload_to='')),
                ('width', models.FloatField(verbose_name='Ширина изображения')),
                ('height', models.FloatField(verbose_name='Высота изображения')),
                ('parent_picture', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pictures', to='picture.picture', verbose_name='Родительская картинка')),
            ],
            options={
                'verbose_name': 'Картинка',
                'verbose_name_plural': 'Картинки',
            },
        ),
    ]
