# Generated by Django 3.1.7 on 2021-09-18 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=1000, null=True, verbose_name='URL изображения')),
                ('picture', models.ImageField(blank=True, upload_to='')),
            ],
            options={
                'verbose_name': 'Картинка',
                'verbose_name_plural': 'Картинки',
            },
        ),
        migrations.CreateModel(
            name='PictureInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название изображения')),
                ('width', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Ширина изображения')),
                ('height', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Высота изображения')),
                ('parent_picture', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='picture_information_parent', to='picture.picture', verbose_name='Родительская картинка')),
                ('picture', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='picture_information', to='picture.picture', verbose_name='Картинка')),
            ],
            options={
                'verbose_name': 'Информация о картинке',
                'verbose_name_plural': 'Информация о картинках',
            },
        ),
    ]
