# Generated by Django 3.1.7 on 2021-09-18 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0002_auto_20210918_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='height',
            field=models.PositiveSmallIntegerField(blank=True, verbose_name='Высота изображения'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='width',
            field=models.PositiveSmallIntegerField(blank=True, verbose_name='Ширина изображения'),
        ),
    ]
