# Generated by Django 3.1.7 on 2021-09-18 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0003_auto_20210918_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='height',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Высота изображения'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='url',
            field=models.SlugField(null=True, verbose_name='URL изображения'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='width',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Ширина изображения'),
        ),
    ]
